FROM rabbitmq:3.7-management

RUN apt-get update && apt-get install wget curl nodejs npm -y

RUN wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez
RUN mv rabbitmq_delayed_message_exchange-3.8.0.ez plugins

RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange

COPY . .

RUN npm install

CMD rabbitmq-server & sleep 10 ; npm test