// Generated by CoffeeScript 1.12.1
(function() {
  var Connection, Job, Queue, Timeout, _;

  try {
    require('source-map-support').install();
  } catch (error) {}

  Connection = require('./connection');

  Queue = require('./queue');

  Job = require('./job');

  Timeout = require('callback-timeout');

  _ = require('lodash');

  module.exports = function(options, cb) {
    var connection;
    connection = new Connection(options);
    connection.connect(function(err) {
      if (err) {
        return typeof cb === "function" ? cb(err) : void 0;
      }
      setTimeout((function() {
        var name, queueopts, ref, results;
        ref = options.queues;
        results = [];
        for (name in ref) {
          queueopts = ref[name];
          if (options.enabled !== false) {
            results.push(connection.createQueue(name, queueopts));
          }
        }
        return results;
      }), 5000);
      return typeof cb === "function" ? cb(null, connection) : void 0;
    });
    return connection;
  };

  module.exports.Connection = Connection;

  module.exports.Queue = Queue;

  module.exports.Job = Job;

}).call(this);

//# sourceMappingURL=beatrix.js.map
