// Generated by CoffeeScript 1.12.1
(function() {
  var Connection, Job, Queue, Timeout, _;

  try {
    require('source-map-support').install();
  } catch (error) {}

  Connection = require('./connection');

  Queue = require('./queue');

  Job = require('./job');

  Timeout = require('callback-timeout');

  _ = require('lodash');

  module.exports = function(options, cb) {
    var connection;
    connection = new Connection(options);
    return connection.connect(function(err) {
      var name, queueopts, ref;
      if (err) {
        return cb(err);
      }
      ref = options.queues;
      for (name in ref) {
        queueopts = ref[name];
        if (options.enabled !== false) {
          connection.createQueue(name, queueopts);
        }
      }
      return cb(null, connection);
    });
  };

  module.exports.Connection = Connection;

  module.exports.Queue = Queue;

  module.exports.Job = Job;

}).call(this);

//# sourceMappingURL=beatrix.js.map
